app/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Length, DataRequired

# =======================================================================================================================

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=4, max=120)])
    description = TextAreaField('Description', validators=[DataRequired(), Length(max=300)])
    tags = StringField('Tags', validators=[DataRequired(), Length(max=200)])
    content = TextAreaField('Post Content', validators=[DataRequired(), Length(min=10)])
    image_file = FileField('Upload Image', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')
    
    

app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Post


main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
@main.route('/index')
def index():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=4)
    return render_template('index.html', title='Home Page', posts=posts)


@main.route('/about')
def about_page():
    return render_template('about.html', title="About Page")

app/posts/routes.py
from app import db
from flask import render_template, flash, url_for, redirect, request, abort, Blueprint
from app.posts.forms import PostForm
from app.models import User, Post
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)


@posts.route('/post/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=4)
    return render_template('user_posts.html', title=user.username +'Posts', posts=posts, user=user)


# =============================== Post Routes =============================================

@posts.route('/post/new', methods=['POST', 'GET'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, tags=form.tags.data, description=form.description.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Post created', category='success')
        return redirect(url_for('main.index'))
    return render_template('new_post.html', title="Add new Post", form=form, legend='Create Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['POST', 'GET'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data 
        post.tags=form.tags.data
        post.description=form.description.data
        post.content=form.content.data
        db.session.commit()
        flash('Post updated!', category='success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.tags.data = post.tags
        form.description.data = post.description
        form.content.data = post.content
    return render_template('new_post.html', title='Update ' + post.title, post=post, form=form, legend='Update Post')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted!', category='success')
    return redirect(url_for('main.index'))

app/users/routes.py
from app import db, bcrypt
from flask import render_template, flash, url_for, redirect, request, Blueprint
from app.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, ResetPasswordForm, RequestResetForm
from app.models import User
from flask_login import login_user, current_user, logout_user, login_required
from app.users.utils import send_reset_mail, upload_image


users = Blueprint('users', __name__)


@users.route('/register', methods=['POST', 'GET'])
def register_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Sign up successful, please log in', category='success')
        return redirect(url_for('users.login_page'))
    return render_template('register.html', title="Sign Up", form=form)


#===============================================================================

@users.route('/login', methods=['POST', 'GET'])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('Sign In successful', category='success') 
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Incorrect username/password', category='danger')       
    return render_template('login.html', title="Sign In", form=form)


#========================================================================================================

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account_page():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image_file.data:
            image_name = upload_image(form.image_file.data)
            current_user.image_file = image_name
        current_user.email = form.email.data
        current_user.username = form.username.data
        db.session.commit()
        flash('Account updated!', category='success')
        return redirect(url_for('users.account_page'))
    image_file = url_for('static', filename='images/profile_pics/' + current_user.image_file)
    return render_template('account.html', title="My Profile", form=form, image_file=image_file)
    


# =============================== Password Reset =============================================

@users.route('/request_reset', methods=['POST', 'GET'])
def request_reset():
    if current_user.is_authenticated:
        flash('You must be logged out to access password reset page', category='info')
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_mail(user)
        flash('Password reset email sent!', category='success')
        return redirect(url_for('users.request_reset'))
    return render_template('request_token.html', title='Request Password Reset', form=form)




# ------------------------------------------ Reset Password ------------------------------------

@users.route('/reset_password/<token>', methods=['POST', 'GET'])
def reset_password(token):
    if current_user.is_authenticated:
        flash('You must be logged out to access password reset page', category='info')
        return redirect(url_for('main.index'))
    
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid/Expired token!', category='warning')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data)
        user.password = hashed_password
        db.session.commit()
        flash('Password updated', category='success')
        return redirect(url_for('users.login_page'))
    return render_template('reset_password.html', title='Request Password Reset', form=form)

# =========================================================================================================
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/about.html
{% extends 'layout.html' %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

app/templates/account.html
{% extends 'layout.html' %}

{% block content %}
  <form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <h4 class="text-info my-3">
      Update Account
    </h4>

    <div class="row justify-content-center">
      <div class="col-md-4 col-sm 6 mx-auto my-4">
        <img src="{{ image_file }}" alt="Profile Image" class="img-thumbnail rounded-circle" width="125" height="125">
      </div>
    </div>

    <div class="mb-3">
      {{ form.username.label(class='form-label') }}
      {% if form.username.errors %}
          {{ form.username(class='form-control is-invalid', value=current_user.username ) }}
          <div class="invalid-feedback">
            {% for error in form.username.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
      {% else %}
          {{ form.username(class='form-control', value=current_user.username ) }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.email.label(class='form-label') }}

      {% if form.email.errors %}
        {{ form.email(class='form-control is-invalid', value=current_user.email ) }}
        <div class="invalid-feedback">
          {% for error in form.email.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
        {{ form.email(class='form-control', value=current_user.email ) }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.image_file(class='form-control', id='image') }}
      {% if form.image_file.errors %}
      
        {% for error in form.image_file.errors %}
          <small class="text-danger">{{ error }}</small>
        {% endfor %}
        
      {% endif %}
    </div>

    {{ form.submit(class='btn btn-primary') }}

  </form>
{% endblock content %}

app/templates/article.html
<article class="media content-section">
  <div class="media-body">
    <div class="article-metadata">
      <a class="mr-2" href="#">{{ post.author }}</a>
      <small class="text-muted">{{ post.date_posted }}</small>
    </div>
    <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>

app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="row">
      {% for post in posts.items %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="" class="img-fluid rounded-start" alt="{{ post.title }}">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><a href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h5>
                  <p class="card-text">{{ post.description }}</p>
                  <p class="card-text"><small class="text-muted">{{ post.date_posted.strftime('%d-%m-%y') }}</small></p>
                </div>
                <div class="footer my-3">
                  <a href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                </div>
              </div>
            </div>
          </div>
      {% endfor %}
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if posts.has_prev %}
            <li class="page-item"><a class="page-link" href="{{ url_for('main.index', page=posts.prev_num) }}"><<</a></li>
          {% endif %}
          {% for page_num in posts.iter_pages() %}
            {% if page_num%}
              <li class="page-item"><a class="page-link" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a></li>
              {% else %}
              ...
            {% endif %}
          
          {% endfor %}
          {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="{{ url_for('main.index', page=posts.next_num) }}">>></a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" 
    crossorigin="anonymous">
    <title>{{ title if title }} </title>
</head>
<body class="container-fluid">
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand">Navbar</a>
            <div class="nav">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('posts.new_post') }}" class="nav-item nav-link" type="submit">Add Post</a>
                    <a href="{{ url_for('users.logout') }}" class="nav-item nav-link" type="submit">Log Out</a>
                {% else %}
                    <a href="{{ url_for('users.register_page') }}" class="btn btn-outline-info mr-3" type="submit">Register</a>
                    <a href="{{ url_for('users.login_page') }}" class="btn btn-outline-info" type="submit">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <div class="container">

        {% if get_flashed_messages() %}
            {% for category, message in get_flashed_messages(with_categories=True) %}
             <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
            {% endfor %}
        {% endif %}
        
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" 
    crossorigin="anonymous">
</script>
</body>
</html>

app/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="">
    {{ form.hidden_tag() }}
    <h2 class="text-info my-3">
        Sign In
    </h2>
    <div class="mb-3">
        {{ form.email.label(class='form-label') }}

        {% if form.email.errors %}
            {{ form.email(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.email(class='form-control') }}
        {% endif %}

        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        {{ form.password.label(class='form-label') }}
        {% if form.password.errors %}
            {{ form.password(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.password(class='form-control') }}
        {% endif %}
    </div>
    <div class="mb-3 form-check">
        {{ form.remember.label(class='form-check-label') }}
        {{ form.remember(class='form-check-input') }}
    </div>
    {{ form.submit(class='btn btn-primary mb-4') }}
    <p>forgot your password?</p><a href="{{url_for('users.request_reset')}}">click here to reset password</a>
</form>
{% endblock content %}

app/templates/main.html
<main role="main" class="container">
  <div class="row">
    <div class="col-md-8">
      {% block content %}{% endblock %}
    </div>
    <div class="col-md-4">
      <div class="content-section">
        <h3>Our Sidebar</h3>
        <p class='text-muted'>You can put any information here you'd like.
          <ul class="list-group">
            <li class="list-group-item list-group-item-light">Latest Posts</li>
            <li class="list-group-item list-group-item-light">Announcements</li>
            <li class="list-group-item list-group-item-light">Calendars</li>
            <li class="list-group-item list-group-item-light">etc</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>

app/templates/navigation.html
<header class="site-header">
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">Flask Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="/">Home</a>
          <a class="nav-item nav-link" href="/about">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Add Post</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Sign Out</a>
          {% else %}
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>

app/templates/new_post.html
{% extends 'layout.html' %}

{% block content %}
  <form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <h4 class="text-info my-3">
      {{ legend }}
    </h4>

    <!-- <div class="row justify-content-center">
      <div class="col-md-4 col-sm 6 mx-auto my-4">
        <img src="{{ image_file }}" alt="Post Image" class="img-thumbnail" width="250" height="250">
      </div>
    </div> -->

    <div class="mb-3">
      {{ form.title.label(class='form-label') }}
      {% if form.title.errors %}
          {{ form.title(class='form-control is-invalid', value=form.title.data ) }}
          <div class="invalid-feedback">
            {% for error in form.title.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
      {% else %}
          {{ form.title(class='form-control') }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.tags.label(class='form-label') }}
      {% if form.tags.errors %}
          {{ form.tags(class='form-control is-invalid', value=form.tags.data ) }}
          <div class="invalid-feedback">
            {% for error in form.tags.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
      {% else %}
          {{ form.tags(class='form-control') }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.description.label(class='form-label') }}
      {% if form.description.errors %}
          {{ form.description(class='form-control is-invalid', value=form.description.data ) }}
          <div class="invalid-feedback">
            {% for error in form.description.errors %}
              <span>{{ error }}</span>
            {% endfor %}
          </div>
      {% else %}
          {{ form.description(class='form-control') }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.content.label(class='form-label') }}

      {% if form.content.errors %}
        {{ form.content(class='form-control is-invalid', value=form.content.data ) }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
            <span>{{ error }}</span>
          {% endfor %}
        </div>
      {% else %}
        {{ form.content(class='form-control') }}
      {% endif %}
    </div>

    <div class="mb-3">
      {{ form.image_file(class='form-control', id='image') }}
      {% if form.image_file.errors %}
      
        {% for error in form.image_file.errors %}
          <small class="text-danger">{{ error }}</small>
        {% endfor %}
        
      {% endif %}
    </div>

    {{ form.submit(class='btn btn-primary') }}

  </form>
{% endblock content %}

app/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <section class="py-3">
        <h3 class="px-2">
            {{ post.title }}
        </h3>
        <p class="px-2 py-3">
            {{ post.content }}
        </p>
        <div class="d-flex justidy-content-between">
            <span class="d-inline-block ml-auto">{{ post.date_posted.strftime('%d-%m-%y') }}</span>           
        </div>
        <div class="footer my-3 d-flex justify-content-between">
            <div class="creator">
              <a href="{{ url_for('posts.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            </div>
            {% if post.author == current_user %}
              <div class="creator">
                <a class="btn btn-sm btn-warning" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                <button class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
              </div>
            {% endif %}
          </div>
    </section>
    <!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-body">
          <p>Are you sure you want to delete this post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id)}}" method="post">
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

app/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="">
    {{ form.hidden_tag() }}
    <h2 class="text-info my-3">
        Sign Up
    </h2>
    <div class="mb-3">
        {{ form.username.label(class='form-label') }}
        {% if form.username.errors %}
            {{ form.username(class='form-control is-invalid', value=form.username.data) }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.username(class='form-control') }}
        {% endif %}
    </div>
    <div class="mb-3">
        {{ form.email.label(class='form-label') }}

        {% if form.email.errors %}
            {{ form.email(class='form-control is-invalid', value=form.email.data ) }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.email(class='form-control') }}
        {% endif %}

        <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
    </div>
    <div class="mb-3">
        {{ form.password.label(class='form-label') }}
        {% if form.password.errors %}
            {{ form.password(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.password(class='form-control') }}
        {% endif %}
    </div>
    <div class="mb-3">
        {{ form.confirm_password.label(class='form-label') }}
        {% if form.confirm_password.errors %}
            {{ form.confirm_password(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.confirm_password(class='form-control') }}
        {% endif %}
    </div>
    {{ form.submit(class='btn btn-primary') }}
</form>
{% endblock content %}

app/templates/request_token.html
{% extends 'layout.html' %}

{% block content %}
<form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="">
    {{ form.hidden_tag() }}
    <h2 class="text-info my-3">
        Request password reset token
    </h2>
    <div class="mb-3">
        {{ form.email.label(class='form-label') }}

        {% if form.email.errors %}
            {{ form.email(class='form-control is-invalid', value=form.email.data ) }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.email(class='form-control') }}
        {% endif %}
    </div>
    {{ form.submit(class='btn btn-primary') }}
</form>
{% endblock content %}

app/templates/reset_password.html
{% extends 'layout.html' %}

{% block content %}
<form class="col-8 mx-auto bg-light px-4 py-3" method="post" action="">
    {{ form.hidden_tag() }}
    <h2 class="text-info my-3">
        Reset Password
    </h2>
    <div class="mb-3">
        {{ form.password.label(class='form-label') }}
        {% if form.password.errors %}
            {{ form.password(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.password(class='form-control') }}
        {% endif %}
    </div>
    <div class="mb-3">
        {{ form.confirm_password.label(class='form-label') }}
        {% if form.confirm_password.errors %}
            {{ form.confirm_password(class='form-control is-invalid') }}
            <div class="invalid-feedback">
                {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
        {% else %}
            {{ form.confirm_password(class='form-control') }}
        {% endif %}
    </div>
    {{ form.submit(class='btn btn-primary') }}
</form>
{% endblock content %}

app/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
<div class="row">
    <h3 class="p-3 bg-light">{{ user.username }} Posts ({{ posts.total }})</h3>
</div>
    <div class="row">
      {% for post in posts.items %}
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="" class="img-fluid rounded-start" alt="{{ post.title }}">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title"><a href="{{ url_for('posts.post', post_id = post.id) }}">{{ post.title }}</a></h5>
                  <p class="card-text">{{ post.description }}</p>
                  <p class="card-text"><small class="text-muted">{{ post.date_posted.strftime('%d-%m-%y') }}</small></p>
                </div>
              </div>
            </div>
          </div>
      {% endfor %}
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {% if posts.has_prev %}
            <li class="page-item"><a class="page-link" href="{{ url_for('posts.user_posts', username=user.username, page=posts.prev_num) }}"><<</a></li>
          {% endif %}
          {% for page_num in posts.iter_pages() %}
            {% if page_num%}
              <li class="page-item"><a class="page-link" href="{{ url_for('posts.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
              {% else %}
              ...
            {% endif %}
          
          {% endfor %}
          {% if posts.has_next %}
            <li class="page-item"><a class="page-link" href="{{ url_for('posts.user_posts', username=user.username, page=posts.next_num) }}">>></a></li>
          {% endif %}
        </ul>
      </nav>
    </div>
{% endblock content %}